os:
  - linux

language: go
go:
  - "1.17"

services:
  - docker

env:
  global:
    # Required
    - OS=linux

stages:
  - test-e2e

jobs:
  include:
    - stage: test-e2e
      name: "Run e2e tests ..."
      script:
        - make test-e2e-local
